import * as WebBrowser from "expo-web-browser";
import { useEffect, useState } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import type { Batch, Coupon, Course, PayoutHistory, PayoutLedger, Refund, Session } from "./api";
import { appStyles as s } from "./appStyles";
import { AdminCertificatesTab, MerchantCertificatesTab } from "./certificates";
import { Button, EmptyState, Icon, Metric, SectionTitle, Tag, colors, styles as uiBase } from "./ui";

const ui: any = { ...uiBase, smallMuted: { color: colors.muted, fontSize: 12, lineHeight: 18 } };

export function MerchantScreen(props: any) {
  const { data, courses: mcourses, batches, coupons, payouts, insights, tab, setTab, showCourseForm, setShowCourseForm, courseForm, setCourseForm, showBatchForm, setShowBatchForm, batchForm, setBatchForm, showCouponForm, setShowCouponForm, couponForm, setCouponForm, attendance, sessionForBatch, onLoadAttendance, onCloseAttendance, onMarkSessionAttendance, onAddSession, onRemoveSession, onLoad, onCreateCourse, onCreateBatch, onCreateCoupon, onSignOut, token, onMessage, onError } = props;
  useEffect(() => { onLoad(); }, [onLoad]);
  const tabs = ["Overview", "Courses", "Batches", "Coupons", "Certificates", "Insights", "Payouts"];
  const published = mcourses.filter((c: Course) => c.status === "published");
  return <><Header title="Institute portal" action="Sign out" onAction={onSignOut} /><Tag>MERCHANT / INSTITUTE</Tag><Text style={s.h1}>Build a learning community.</Text><Text style={s.body}>Courses, batches, coupons, certificates, insights, and payouts from one place.</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.horizontal} contentContainerStyle={{ paddingHorizontal: 2, gap: 8 }}>{tabs.map(item => <Pressable key={item} testID={`m-tab-${item}`} onPress={() => setTab(item)} style={[s.pill, tab === item && s.activePill, { flexShrink: 0 }]}><Text style={[s.pillText, tab === item && { color: colors.white }]}>{item}</Text></Pressable>)}</ScrollView>
    {!data ? <ActivityIndicator color={colors.green} /> : tab === "Overview" ? <OverviewTab data={data} setTab={setTab} setShowCourseForm={setShowCourseForm} /> :
      tab === "Courses" ? <CoursesTab mcourses={mcourses} showCourseForm={showCourseForm} setShowCourseForm={setShowCourseForm} courseForm={courseForm} setCourseForm={setCourseForm} onCreateCourse={onCreateCourse} /> :
      tab === "Batches" ? <BatchesTab published={published} batches={batches} showBatchForm={showBatchForm} setShowBatchForm={setShowBatchForm} batchForm={batchForm} setBatchForm={setBatchForm} onCreateBatch={onCreateBatch} sessionForBatch={sessionForBatch} onAddSession={onAddSession} onRemoveSession={onRemoveSession} attendance={attendance} onLoadAttendance={onLoadAttendance} onCloseAttendance={onCloseAttendance} onMarkSessionAttendance={onMarkSessionAttendance} setSessionForBatch={props.setSessionForBatch} /> :
      tab === "Coupons" ? <CouponsTab coupons={coupons} mcourses={mcourses} showCouponForm={showCouponForm} setShowCouponForm={setShowCouponForm} couponForm={couponForm} setCouponForm={setCouponForm} onCreateCoupon={onCreateCoupon} /> :
      tab === "Certificates" ? <MerchantCertificatesTab token={token} onMessage={onMessage} onError={onError} /> :
      tab === "Insights" ? <InsightsTab insights={insights} /> :
      <PayoutsTab payouts={payouts} />}
  </>;
}

function Header({ title, onBack, action, onAction }: any) { return <View style={s.header}>{onBack ? <Pressable onPress={onBack} style={s.iconButton}><Icon name="arrow-back" size={21} /></Pressable> : <View style={s.brand}><Text style={s.brandText}>C</Text></View>}<Text style={s.headerTitle}>{title || "CORZAAR"}</Text>{action ? <Pressable onPress={onAction}><Text style={ui.link}>{action}</Text></Pressable> : <View style={{ width: 26 }} />}</View>; }

function OverviewTab({ data, setTab, setShowCourseForm }: any) { return <><View style={s.metrics}><Metric label="Active courses" value={data.active_courses} icon="book-outline" /><Metric label="Enrollments" value={data.enrollments} icon="people-outline" tone="orange" /><Metric label="Revenue ₹" value={Math.round(data.revenue || 0)} icon="cash-outline" /></View><View style={s.info}><Text style={ui.cardTitle}>Your institute</Text><Text style={s.body}>{data.institute?.name || "Institute profile pending"} · Status: {data.institute?.status || "pending"}</Text><Text style={s.body}>Publish a course, add a batch, then track attendance session-by-session.</Text><Button label="Create a course" small onPress={() => { setTab("Courses"); setShowCourseForm(true); }} /></View><SectionTitle title="Announcements" />{data.announcements?.map((item: string) => <View style={s.listRow} key={item}><Icon name="megaphone-outline" size={19} color={colors.green} /><Text style={s.listText}>{item}</Text></View>)}</>; }

function CoursesTab({ mcourses, showCourseForm, setShowCourseForm, courseForm, setCourseForm, onCreateCourse }: any) { return <><View style={s.result}><Text style={ui.h2}>Your courses</Text><Button testID="add-course" label="Add course" small onPress={() => setShowCourseForm(!showCourseForm)} /></View>{showCourseForm && <View style={s.info}><Text style={s.label}>Title</Text><TextInput testID="course-title" style={s.formInput} value={courseForm.title} onChangeText={(title: string) => setCourseForm({ ...courseForm, title })} placeholder="e.g. Advanced Excel" placeholderTextColor={colors.muted} /><Text style={s.label}>Description</Text><TextInput style={[s.formInput, { height: 80 }]} value={courseForm.description} onChangeText={(description: string) => setCourseForm({ ...courseForm, description })} multiline placeholder="What will students learn?" placeholderTextColor={colors.muted} /><Text style={s.label}>Category</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingVertical: 4 }}>{["Design", "Technology", "Business", "Marketing"].map(cat => <Pressable key={cat} onPress={() => setCourseForm({ ...courseForm, category: cat })} style={[s.pill, courseForm.category === cat && s.activePill, { flexShrink: 0 }]}><Text style={[s.pillText, courseForm.category === cat && { color: colors.white }]}>{cat}</Text></Pressable>)}</ScrollView><Text style={s.label}>Duration</Text><TextInput style={s.formInput} value={courseForm.duration} onChangeText={(duration: string) => setCourseForm({ ...courseForm, duration })} placeholder="8 weeks" placeholderTextColor={colors.muted} /><Text style={s.label}>Fee (₹)</Text><TextInput testID="course-fees" style={s.formInput} value={courseForm.fees} onChangeText={(fees: string) => setCourseForm({ ...courseForm, fees })} keyboardType="numeric" placeholder="0 for free" placeholderTextColor={colors.muted} /><Button testID="course-submit" label="Submit for admin review" onPress={onCreateCourse} /></View>}{mcourses.length ? mcourses.map((c: Course) => <View key={c.id} style={s.row}><View style={s.rowIcon}><Icon name="book-outline" size={17} color={colors.green} /></View><View style={{ flex: 1 }}><Text style={ui.cardTitle}>{c.title}</Text><Text style={ui.smallMuted}>{c.category} · ₹{Number(c.fees || 0).toLocaleString("en-IN")}</Text></View><Tag tone={c.status === "published" ? "green" : c.status === "under_review" ? "orange" : "gray"}>{c.status}</Tag></View>) : <EmptyState icon="library-outline" title="No courses yet" body="Create a course. Admin approves before it appears in discovery." />}</>; }

function BatchesTab({ published, batches, showBatchForm, setShowBatchForm, batchForm, setBatchForm, onCreateBatch, sessionForBatch, onAddSession, onRemoveSession, attendance, onLoadAttendance, onCloseAttendance, onMarkSessionAttendance }: any) {
  const [newDate, setNewDate] = useState("");
  return <><View style={s.result}><Text style={ui.h2}>Your batches</Text><Button testID="add-batch" label="New batch" small onPress={() => setShowBatchForm(!showBatchForm)} /></View>
    {showBatchForm && <View style={s.info}><Text style={s.label}>Course</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingVertical: 4 }}>{published.map((c: Course) => <Pressable key={c.id} onPress={() => setBatchForm({ ...batchForm, course_id: c.id })} style={[s.pill, batchForm.course_id === c.id && s.activePill, { flexShrink: 0 }]}><Text style={[s.pillText, batchForm.course_id === c.id && { color: colors.white }]}>{c.title}</Text></Pressable>)}</ScrollView>{!published.length && <Text style={ui.smallMuted}>Publish a course first (admin approval).</Text>}<Text style={s.label}>Schedule (include days, e.g. &quot;Mon Wed 7-9pm&quot;)</Text><TextInput style={s.formInput} value={batchForm.schedule} onChangeText={(schedule: string) => setBatchForm({ ...batchForm, schedule })} placeholderTextColor={colors.muted} /><Text style={s.label}>Coordinator</Text><TextInput style={s.formInput} value={batchForm.coordinator} onChangeText={(coordinator: string) => setBatchForm({ ...batchForm, coordinator })} placeholderTextColor={colors.muted} /><View style={{ flexDirection: "row", gap: 8 }}><View style={{ flex: 1 }}><Text style={s.label}>Start (YYYY-MM-DD)</Text><TextInput style={s.formInput} value={batchForm.start_date} onChangeText={(start_date: string) => setBatchForm({ ...batchForm, start_date })} placeholder="2026-04-01" placeholderTextColor={colors.muted} /></View><View style={{ flex: 1 }}><Text style={s.label}>End</Text><TextInput style={s.formInput} value={batchForm.end_date} onChangeText={(end_date: string) => setBatchForm({ ...batchForm, end_date })} placeholder="2026-06-01" placeholderTextColor={colors.muted} /></View></View><Text style={s.label}>Seats</Text><TextInput style={s.formInput} value={batchForm.capacity} onChangeText={(capacity: string) => setBatchForm({ ...batchForm, capacity })} keyboardType="numeric" placeholderTextColor={colors.muted} /><Text style={s.label}>Live class link</Text><TextInput style={s.formInput} value={batchForm.meet_link} onChangeText={(meet_link: string) => setBatchForm({ ...batchForm, meet_link })} placeholder="https://meet.google.com/..." placeholderTextColor={colors.muted} autoCapitalize="none" /><Text style={ui.smallMuted}>Sessions auto-generate from schedule days between start &amp; end. Edit them after create.</Text><Button label="Create batch" onPress={onCreateBatch} /></View>}
    {batches.length ? batches.map((b: Batch) => <View key={b.id} style={s.info}><View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}><Text style={ui.cardTitle}>{b.course_title || b.course_id}</Text><Tag tone="green">{b.status}</Tag></View><Text style={ui.smallMuted}>{b.schedule} · Seats {b.capacity}</Text><Text style={ui.smallMuted}>{b.start_date} → {b.end_date}</Text>{b.meet_link ? <Pressable onPress={() => WebBrowser.openBrowserAsync(b.meet_link!)}><Text style={ui.link}>Open live class link</Text></Pressable> : null}
      <Text style={s.label}>Sessions ({b.sessions?.length || 0})</Text>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 6 }}>{b.sessions?.slice(0, 12).map((sess: Session) => <View key={sess.id} style={[s.pill, { flexShrink: 0, backgroundColor: colors.soft }]}><Text style={s.pillText}>{sess.date}</Text><Pressable onPress={() => onRemoveSession(b.id, sess.id)} hitSlop={4}><Icon name="close" size={14} color={colors.red} /></Pressable></View>)}</ScrollView>
      {sessionForBatch === b.id ? <View style={{ flexDirection: "row", gap: 8, marginTop: 6 }}><TextInput style={[s.formInput, { flex: 1, marginTop: 0, marginBottom: 0 }]} value={newDate} onChangeText={setNewDate} placeholder="YYYY-MM-DD" placeholderTextColor={colors.muted} /><Button label="Add" small onPress={() => { if (newDate) { onAddSession(b.id, newDate); setNewDate(""); } }} /></View> : null}
      <View style={{ flexDirection: "row", gap: 8, marginTop: 6 }}><Button label="Attendance" small secondary onPress={() => onLoadAttendance(b.id)} /><Button label={sessionForBatch === b.id ? "Done" : "Add session"} small secondary onPress={() => props.setSessionForBatch?.(sessionForBatch === b.id ? null : b.id)} /></View>
    </View>) : <EmptyState icon="calendar-outline" title="No batches yet" body="Create a batch. Sessions auto-generate from your weekly schedule." />}
    {attendance && <AttendanceModal attendance={attendance} onClose={onCloseAttendance} onMark={onMarkSessionAttendance} />}
  </>;
}

function AttendanceModal({ attendance, onClose, onMark }: any) {
  const [pickedSession, setPickedSession] = useState<string | null>(attendance.batch?.sessions?.[0]?.id || null);
  const session = attendance.batch?.sessions?.find((sess: Session) => sess.id === pickedSession);
  return <Modal transparent animationType="slide" onRequestClose={onClose}><View style={s.modalWrap}><View style={s.modal}><View style={s.handle} /><View style={s.modalHeader}><Text style={ui.h2}>Attendance</Text><Pressable onPress={onClose} style={s.iconButton}><Icon name="close" size={20} /></Pressable></View><Text style={s.body}>{attendance.batch?.course_title} · {attendance.students.length} learners</Text>
    <Text style={s.label}>Session</Text>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{attendance.batch?.sessions?.map((sess: Session) => <Pressable key={sess.id} onPress={() => setPickedSession(sess.id)} style={[s.pill, pickedSession === sess.id && s.activePill, { flexShrink: 0 }]}><Text style={[s.pillText, pickedSession === sess.id && { color: colors.white }]}>{sess.date}</Text></Pressable>)}</ScrollView>
    <ScrollView style={{ maxHeight: 380, marginTop: 8 }}>{attendance.students.length && session ? attendance.students.map((st: any) => { const mark = st.marks?.[pickedSession!]; return <View key={st.id} style={s.row}><View style={{ flex: 1 }}><Text style={ui.cardTitle}>{st.name}</Text><Text style={ui.smallMuted}>Overall: {st.present}/{st.sessions}{mark === true ? " · marked present" : mark === false ? " · marked absent" : ""}</Text></View><Pressable onPress={() => onMark(attendance.batch.id, pickedSession, st.id, true)} style={s.iconButton}><Icon name="checkmark-circle" size={22} color={mark === true ? colors.green : colors.muted} /></Pressable><Pressable onPress={() => onMark(attendance.batch.id, pickedSession, st.id, false)} style={s.iconButton}><Icon name="close-circle" size={22} color={mark === false ? colors.red : colors.muted} /></Pressable></View>; }) : <EmptyState icon="people-outline" title={session ? "No enrolled students yet" : "Pick a session"} body={session ? "Attendance appears once students enroll into this course." : "Choose a session above to mark attendance."} />}</ScrollView>
  </View></View></Modal>;
}

function CouponsTab({ coupons, mcourses, showCouponForm, setShowCouponForm, couponForm, setCouponForm, onCreateCoupon }: any) { return <><View style={s.result}><Text style={ui.h2}>Your coupons</Text><Button testID="add-coupon" label="New coupon" small onPress={() => setShowCouponForm(!showCouponForm)} /></View>{showCouponForm && <View style={s.info}><Text style={s.label}>Code</Text><TextInput testID="coupon-code" style={s.formInput} value={couponForm.code} onChangeText={(code: string) => setCouponForm({ ...couponForm, code })} autoCapitalize="characters" placeholder="LEARN25" placeholderTextColor={colors.muted} /><Text style={s.label}>Description</Text><TextInput style={s.formInput} value={couponForm.description} onChangeText={(description: string) => setCouponForm({ ...couponForm, description })} placeholder="Season scholarship" placeholderTextColor={colors.muted} /><Text style={s.label}>Discount percent</Text><TextInput style={s.formInput} value={couponForm.discount_percent} onChangeText={(discount_percent: string) => setCouponForm({ ...couponForm, discount_percent })} keyboardType="numeric" placeholderTextColor={colors.muted} /><Text style={s.label}>Restrict to course (optional)</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingVertical: 4 }}><Pressable onPress={() => setCouponForm({ ...couponForm, course_id: "" })} style={[s.pill, !couponForm.course_id && s.activePill, { flexShrink: 0 }]}><Text style={[s.pillText, !couponForm.course_id && { color: colors.white }]}>All courses</Text></Pressable>{mcourses.map((c: Course) => <Pressable key={c.id} onPress={() => setCouponForm({ ...couponForm, course_id: c.id })} style={[s.pill, couponForm.course_id === c.id && s.activePill, { flexShrink: 0 }]}><Text style={[s.pillText, couponForm.course_id === c.id && { color: colors.white }]}>{c.title}</Text></Pressable>)}</ScrollView><Button testID="coupon-submit" label="Submit for admin approval" onPress={onCreateCoupon} /></View>}{coupons.length ? coupons.map((cp: Coupon) => <View key={cp.id} style={s.row}><View style={s.rowIcon}><Icon name="pricetag-outline" size={17} color={colors.green} /></View><View style={{ flex: 1 }}><Text style={ui.cardTitle}>{cp.code} · {cp.discount_percent}% off</Text><Text style={ui.smallMuted}>{cp.description || "Merchant coupon"}</Text></View><Tag tone={cp.status === "approved" ? "green" : cp.status === "pending" ? "orange" : "gray"}>{cp.status}</Tag></View>) : <EmptyState icon="pricetag-outline" title="No coupons yet" body="Create discount codes. Admin approves before they go live." />}</>; }

function PayoutsTab({ payouts }: any) { if (!payouts) return <ActivityIndicator color={colors.green} />; return <><View style={s.metrics}><Metric label="Earned ₹" value={Math.round(payouts.gross || 0)} icon="cash-outline" /><Metric label="Paid out ₹" value={Math.round(payouts.paid_out || 0)} icon="checkmark-circle-outline" /><Metric label="Pending ₹" value={Math.round(payouts.pending || 0)} icon="hourglass-outline" tone="orange" /></View><View style={s.info}><Text style={ui.cardTitle}>How payouts work</Text><Text style={s.body}>Admin transfers your pending balance to your bank and records each payout here. After deploy with live Stripe keys, this upgrades to automated Stripe Connect splits.</Text></View><SectionTitle title="Payout history" />{payouts.history?.length ? payouts.history.map((h: PayoutHistory) => <View key={h.id} style={s.row}><View style={s.rowIcon}><Icon name="cash-outline" size={17} color={colors.green} /></View><View style={{ flex: 1 }}><Text style={ui.cardTitle}>₹{Number(h.amount).toLocaleString("en-IN")}</Text><Text style={ui.smallMuted}>{h.method} · {new Date(h.created_at).toLocaleDateString()}{h.reference ? ` · Ref ${h.reference}` : ""}</Text></View><Tag tone="green">{h.status}</Tag></View>) : <EmptyState icon="cash-outline" title="No payouts yet" body="Payouts appear here once admin transfers your earnings." />}</>; }

function InsightsTab({ insights }: any) {
  if (!insights) return <ActivityIndicator color={colors.green} />;
  const trend: any[] = insights.rating_trend || [];
  const latest = trend[trend.length - 1];
  const prev = trend[trend.length - 2];
  const delta = latest && prev ? (latest.average - prev.average).toFixed(1) : "0.0";
  return <><View style={s.metrics}><Metric label="Latest rating" value={latest ? latest.average : 0} icon="star-outline" /><Metric label="Reviews this week" value={latest ? latest.count : 0} icon="chatbubbles-outline" tone="orange" /><Metric label="Trend" value={`${Number(delta) >= 0 ? "+" : ""}${delta}`} icon={Number(delta) >= 0 ? "trending-up-outline" : "trending-down-outline"} /></View>
    <SectionTitle title="Rating trend (by week)" />
    {trend.length ? <View style={s.info}>{trend.slice(-6).map(w => <View key={w.week} style={{ marginBottom: 8 }}><View style={{ flexDirection: "row", justifyContent: "space-between" }}><Text style={ui.smallMuted}>Week of {w.week}</Text><Text style={ui.rating}>{w.average} · {w.count} reviews</Text></View><View style={s.bar}><View style={[s.barFill, { width: `${(w.average / 5) * 100}%` }]} /></View></View>)}</View> : <EmptyState icon="analytics-outline" title="No reviews yet" body="Reviews from enrolled students will build your rating trend." />}
    <SectionTitle title="Most-liked courses" />
    {insights.top_courses?.length ? insights.top_courses.map((c: any) => <View key={c.id} style={s.row}><View style={s.rowIcon}><Icon name="book-outline" size={17} color={colors.green} /></View><View style={{ flex: 1 }}><Text style={ui.cardTitle}>{c.title}</Text><Text style={ui.smallMuted}>{c.students} learners · {c.reviews_count} reviews</Text></View><Text style={ui.rating}>★ {c.rating}</Text></View>) : <EmptyState icon="library-outline" title="No course data yet" body="Course engagement appears here once students enroll and rate." />}
    <SectionTitle title="Where students drop off" />
    {insights.curriculum_dropoff?.length ? insights.curriculum_dropoff.map((c: any) => <View key={c.id} style={s.info}><Text style={ui.cardTitle}>{c.title} · {c.enrolled} learners</Text>{c.items.map((it: any) => <View key={it.item} style={{ marginTop: 6 }}><View style={{ flexDirection: "row", justifyContent: "space-between" }}><Text style={ui.smallMuted}>{it.item}</Text><Text style={ui.smallMuted}>{it.pct}%</Text></View><View style={s.bar}><View style={[s.barFill, { width: `${it.pct}%`, backgroundColor: it.pct >= 60 ? colors.green : it.pct >= 30 ? colors.orange : colors.red }]} /></View></View>)}</View>) : <EmptyState icon="git-branch-outline" title="Drop-off will show here" body="Once enrolled students start ticking curriculum items, this shows where they slow down." />}
  </>;
}

export function AdminScreen(props: any) {
  const { data, institutes, coursesList, coupons, refunds, logs, payouts, cashouts, payoutForm, setPayoutForm, cashoutRef, setCashoutRef, onRecordPayout, onCashout, onLoad, onInstitute, onCourse, onCoupon, onRefund, onSignOut, token, onMessage, onError } = props;
  const [tab, setTab] = useState("Institutes");
  useEffect(() => { onLoad(); }, [onLoad]);
  const tabs = ["Institutes", "Courses", "Coupons", "Refunds", "Certificates", "Payouts", "Cashouts", "Audit"];
  return <><Header title="Admin oversight" action="Sign out" onAction={onSignOut} /><Tag tone="orange">ADMIN CONTROL CENTER</Tag><Text style={s.h1}>Keep CORZAAR trusted.</Text><Text style={s.body}>Review the marketplace, protect students, and keep every action auditable.</Text>
    {data ? <View style={s.metrics}><Metric label="Students" value={data.total_students} icon="people-outline" /><Metric label="Institutes" value={data.active_institutes} icon="business-outline" tone="orange" /><Metric label="Courses" value={data.active_courses} icon="book-outline" /></View> : <ActivityIndicator color={colors.green} />}
    {data && <View style={s.metrics}><Metric label="Pending courses" value={data.pending_courses} icon="hourglass-outline" tone="orange" /><Metric label="Pending coupons" value={data.pending_coupons} icon="pricetag-outline" /><Metric label="Pending refunds" value={data.pending_refunds} icon="return-up-back-outline" tone="orange" /></View>}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} style={s.horizontal} contentContainerStyle={{ paddingHorizontal: 2, gap: 8 }}>{tabs.map(item => <Pressable key={item} testID={`a-tab-${item}`} onPress={() => setTab(item)} style={[s.pill, tab === item && s.activePill, { flexShrink: 0 }]}><Text style={[s.pillText, tab === item && { color: colors.white }]}>{item}</Text></Pressable>)}</ScrollView>
    <SectionTitle title={tab} action="Refresh" onAction={onLoad} />
    {tab === "Institutes" ? (institutes.length ? institutes.map((item: any) => <View key={item.id} style={s.approval}><View style={ui.logo}><Text style={ui.logoText}>{item.name.charAt(0)}</Text></View><View style={{ flex: 1 }}><Text style={ui.cardTitle}>{item.name}</Text><Text style={ui.smallMuted}>{item.city} · {item.status}</Text></View>{item.status === "pending" ? <View style={s.inline}><Pressable onPress={() => onInstitute(item.id, "rejected")}><Icon name="close-circle-outline" size={24} color={colors.red} /></Pressable><Pressable onPress={() => onInstitute(item.id, "approved")}><Icon name="checkmark-circle-outline" size={24} color={colors.green} /></Pressable></View> : <Tag tone={item.status === "approved" ? "green" : "orange"}>{item.status}</Tag>}</View>) : <EmptyState icon="business-outline" title="All caught up" body="No pending institutes at the moment." />)
      : tab === "Courses" ? (coursesList.length ? coursesList.map((c: Course) => <View key={c.id} style={s.approval}><View style={s.rowIcon}><Icon name="book-outline" size={17} color={colors.green} /></View><View style={{ flex: 1 }}><Text style={ui.cardTitle}>{c.title}</Text><Text style={ui.smallMuted}>{c.category} · ₹{Number(c.fees || 0).toLocaleString("en-IN")} · {c.status}</Text></View>{c.status === "under_review" ? <View style={s.inline}><Pressable onPress={() => onCourse(c.id, "rejected")}><Icon name="close-circle-outline" size={24} color={colors.red} /></Pressable><Pressable onPress={() => onCourse(c.id, "published")}><Icon name="checkmark-circle-outline" size={24} color={colors.green} /></Pressable></View> : <Tag tone={c.status === "published" ? "green" : "gray"}>{c.status}</Tag>}</View>) : <EmptyState icon="library-outline" title="No courses to review" body="Merchant course submissions will appear here." />)
      : tab === "Coupons" ? (coupons.length ? coupons.map((cp: Coupon & { merchant?: any }) => <View key={cp.id} style={s.approval}><View style={s.rowIcon}><Icon name="pricetag-outline" size={17} color={colors.green} /></View><View style={{ flex: 1 }}><Text style={ui.cardTitle}>{cp.code} · {cp.discount_percent}%</Text><Text style={ui.smallMuted}>{cp.description || "Merchant coupon"}{cp.merchant?.full_name ? ` · ${cp.merchant.full_name}` : ""}</Text></View>{cp.status === "pending" ? <View style={s.inline}><Pressable onPress={() => onCoupon(cp.id, "rejected")}><Icon name="close-circle-outline" size={24} color={colors.red} /></Pressable><Pressable onPress={() => onCoupon(cp.id, "approved")}><Icon name="checkmark-circle-outline" size={24} color={colors.green} /></Pressable></View> : <Tag tone={cp.status === "approved" ? "green" : "gray"}>{cp.status}</Tag>}</View>) : <EmptyState icon="pricetag-outline" title="No coupons to review" body="Merchant coupon submissions will appear here." />)
      : tab === "Refunds" ? (refunds.length ? refunds.map((r: Refund) => <View key={r.id} style={s.approval}><View style={s.rowIcon}><Icon name="cash-outline" size={17} color={colors.orange} /></View><View style={{ flex: 1 }}><Text style={ui.cardTitle}>{r.course_title || r.enrollment_id}</Text><Text style={ui.smallMuted}>₹{Number(r.amount || 0).toLocaleString("en-IN")} · {r.student_name || "Learner"}</Text><Text style={ui.smallMuted}>{r.reason}</Text></View>{r.status === "pending" ? <View style={s.inline}><Pressable onPress={() => onRefund(r.id, "rejected")}><Icon name="close-circle-outline" size={24} color={colors.red} /></Pressable><Pressable onPress={() => onRefund(r.id, "approved")}><Icon name="checkmark-circle-outline" size={24} color={colors.green} /></Pressable></View> : <Tag tone={r.status === "approved" || r.status === "processed" ? "green" : "gray"}>{r.status}</Tag>}</View>) : <EmptyState icon="return-up-back-outline" title="No refund requests" body="Student refund requests appear here for review." />)
      : tab === "Certificates" ? <AdminCertificatesTab token={token} onMessage={onMessage} onError={onError} />
      : tab === "Payouts" ? <AdminPayouts payouts={payouts} payoutForm={payoutForm} setPayoutForm={setPayoutForm} onRecordPayout={onRecordPayout} />
      : tab === "Cashouts" ? <AdminCashouts cashouts={cashouts} cashoutRef={cashoutRef} setCashoutRef={setCashoutRef} onAction={onCashout} />
      : (logs.length ? logs.map((l: any) => <View key={l.id} style={s.row}><View style={s.rowIcon}><Icon name="pulse-outline" size={17} color={colors.green} /></View><View style={{ flex: 1 }}><Text style={ui.cardTitle}>{l.action}</Text><Text style={ui.smallMuted}>{l.module} · {l.actor_name || l.role} · {new Date(l.created_at).toLocaleString()}</Text>{l.detail ? <Text style={ui.smallMuted}>{l.detail}</Text> : null}</View></View>) : <EmptyState icon="document-text-outline" title="Nothing to audit yet" body="Every admin and merchant action shows up here for review." />)}
  </>;
}

function AdminCashouts({ cashouts, cashoutRef, setCashoutRef, onAction }: any) {
  const [selected, setSelected] = useState<string | null>(null);
  if (!cashouts) return <ActivityIndicator color={colors.green} />;
  return <>{cashouts.length ? cashouts.map((co: any) => <View key={co.id} style={s.info}><View style={{ flexDirection: "row", alignItems: "center", gap: 10 }}><View style={s.rowIcon}><Icon name="cash-outline" size={17} color={colors.green} /></View><View style={{ flex: 1 }}><Text style={ui.cardTitle}>₹{Number(co.amount).toLocaleString("en-IN")} · {co.student_name || "Learner"}</Text><Text style={ui.smallMuted}>{co.upi_id} · {new Date(co.created_at).toLocaleString()}</Text></View><Tag tone={co.status === "paid" ? "green" : co.status === "rejected" ? "gray" : "orange"}>{co.status}</Tag></View>{co.status === "pending" && (selected === co.id ? <View style={{ gap: 6 }}><TextInput style={s.formInput} value={cashoutRef} onChangeText={setCashoutRef} placeholder="UPI transaction reference" placeholderTextColor={colors.muted} /><View style={{ flexDirection: "row", gap: 8 }}><Button label="Reject" secondary small onPress={() => { onAction(co.id, "rejected"); setSelected(null); }} /><Button label="Mark paid" small onPress={() => { onAction(co.id, "paid"); setSelected(null); }} /></View></View> : <Button label="Process" small onPress={() => { setSelected(co.id); setCashoutRef(""); }} />)}</View>) : <EmptyState icon="wallet-outline" title="No cashouts to process" body="Student UPI cashout requests will appear here." />}</>;
}

function AdminPayouts({ payouts, payoutForm, setPayoutForm, onRecordPayout }: any) {
  const [selected, setSelected] = useState<PayoutLedger | null>(null);
  if (!payouts) return <ActivityIndicator color={colors.green} />;
  return <><Text style={ui.smallMuted}>{payouts.note}</Text>{payouts.ledger?.length ? payouts.ledger.map((l: PayoutLedger) => <View key={l.merchant_id} style={s.approval}><View style={s.rowIcon}><Icon name="business-outline" size={17} color={colors.green} /></View><View style={{ flex: 1 }}><Text style={ui.cardTitle}>{l.institute?.name || l.merchant_name}</Text><Text style={ui.smallMuted}>Earned ₹{Math.round(l.gross).toLocaleString("en-IN")} · Paid ₹{Math.round(l.paid_out).toLocaleString("en-IN")} · Pending ₹{Math.round(l.pending).toLocaleString("en-IN")}</Text></View>{l.pending > 0 ? <Button label="Record payout" small onPress={() => { setSelected(l); setPayoutForm({ ...payoutForm, merchant_id: l.merchant_id, amount: String(Math.round(l.pending)) }); }} /> : <Tag tone="green">Settled</Tag>}</View>) : <EmptyState icon="cash-outline" title="No merchants yet" body="Payouts appear once merchants sell courses." />}
  {selected && <View style={s.info}><Text style={ui.cardTitle}>Record payout · {selected.institute?.name || selected.merchant_name}</Text><Text style={s.label}>Amount (₹)</Text><TextInput style={s.formInput} value={payoutForm.amount} onChangeText={(amount: string) => setPayoutForm({ ...payoutForm, amount })} keyboardType="numeric" placeholderTextColor={colors.muted} /><Text style={s.label}>Method</Text><TextInput style={s.formInput} value={payoutForm.method} onChangeText={(method: string) => setPayoutForm({ ...payoutForm, method })} placeholderTextColor={colors.muted} /><Text style={s.label}>Reference / UTR</Text><TextInput style={s.formInput} value={payoutForm.reference} onChangeText={(reference: string) => setPayoutForm({ ...payoutForm, reference })} placeholderTextColor={colors.muted} /><View style={{ flexDirection: "row", gap: 8 }}><Button label="Cancel" secondary small onPress={() => setSelected(null)} /><Button label="Save payout" small onPress={() => { onRecordPayout(); setSelected(null); }} /></View></View>}
  <SectionTitle title="Recent payouts" />{payouts.history?.length ? payouts.history.slice(0, 10).map((h: PayoutHistory) => <View key={h.id} style={s.row}><View style={s.rowIcon}><Icon name="cash-outline" size={17} color={colors.green} /></View><View style={{ flex: 1 }}><Text style={ui.cardTitle}>₹{Number(h.amount).toLocaleString("en-IN")}</Text><Text style={ui.smallMuted}>{h.method}{h.reference ? ` · ${h.reference}` : ""} · {new Date(h.created_at).toLocaleDateString()}</Text></View><Tag tone="green">{h.status}</Tag></View>) : <EmptyState icon="cash-outline" title="No payouts recorded yet" body="Recorded payouts show here for auditing." />}
  </>;
}
